### ISSUE TITLE
Upload helm chart to chart repository

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/qiskit-serverless#52]
### What is the expected behavior?

Use chart repository to store helm charts

**Comment by akihikokuroda** [comment]
There is one option for the repository [github](https://helm.sh/docs/topics/chart_repository/#github-pages-example)

**Comment by Tansito** [comment]
Oh, sorry @akihikokuroda I added the label `on-hold` but I didn't explain the current status of this. We analyzed the options and the github one with gh-pages is the preferred for us but due to the current structure of the repository using it for documentation plus mono-repo we can't build it. @pacomf is working on a organization for us where we can deliver this, until that moment we will maintain the issue `on-hold`.

**Comment by akihikokuroda** [comment]
I wonder if we can create 3 helm charts (1 main and 2 sub charts) in this repository by restructuring the directory structure and serve those charts in this repo.
